#!/usr/bin/env python3
import time
import urllib.request
from bs4 import BeautifulSoup

#Link parser http://archive.apache.org/dist/struts/2.5.8/
#http://archive.apache.org/dist/struts/
def downloadfile(URL,file_name):
    urllib.request.urlretrieve(URL,filename=file_name)
    time.sleep(10)
    print("Downloaded")

def parse_link(url,file):
    file_name=file
    link = url
    version = link.split("download.php")
    sub_url = version[0]
    last_url= version[1];
    url=sub_url+"download.php/direct" +last_url
    print(url)
    downloadfile(url,file_name)

def read_link(url):
    codeurl = url
    response = urllib.request.urlopen(codeurl)
    #print(response.read())
    soup = BeautifulSoup(response.read(),"lxml")

    links = soup.findAll("a",href=True)

    for link in links:
        file = link['href']
        if file.endswith(".zip"):
            url = file;
            filename = file.split("/")
            file=filename[5]
            parse_link(url,file)
#https://download.moodle.org/download.php/direct/stable29/moodle-latest-29.zip
url = "https://download.moodle.org/releases/legacy/"
read_link(url)
