#!/usr/bin/env python3
import requests
import urllib.request
import os
import sys
import re
import zipfile

#https://wordpress.org/wordpress-4.0.15.zip
PLUGINLIST = "urls.txt"
DESTDIR = "./downloaded/"
DESTFILE = DESTDIR + "download.zip"
regex = re.compile(r'(https://downloads..*?zip)')
print('Opening the file')
urls = open(PLUGINLIST,"r").readlines()

if not os.path.exists(DESTDIR) and not os.path.isdir(DESTDIR):
	print(DESTDIR + "is not a folder or doesn't exist.")
	sys.exit(1)

for url in urls:
	url = url.strip()

	try:
		split_name = url.split("/")

		filename = split_name[3]

		print (filename);
		print('==================')
		print("Starting download of " + url)
		urllib.request.urlretrieve(url, filename)
		print("Downloaded")
	except Exception as e:
		print(e)
		continue
